//
//  DP_Constants.h
//  Upload-iOS
//
//  Created by Danish Ahmed Ansari on 19/03/14.
//  Copyright (c) 2014 Danish Ahmed Ansari. All rights reserved.
//

// ADD THE LOCATION OF THE WEB SERVICES API URL
static NSString * const ImageUploadProjectAPIURLString = @"";

// SEEPZ, Andheri - East, Mumbai Location [THIS CAN BE CHANGED TO ANOTHER LOCATION] - DISTANCE FILTER FROM THIS LOCATION IS 50m RADIUS
#define DP_LATITUDE 19.124118
#define DP_LONGITUDE 72.872320

// CHANGE THIS TO ADJUST THE DISTANCE WITHIN WHICH THE USER IS ABLE TO CAPTURE IMAGES AND SEND THEM TO THE SERVER
#define DP_DISTANCE_RADIUS_FILTER 50000